parameters:
    xidea_book.author.repository.default.class: Xidea\Bundle\BookBundle\Doctrine\ORM\Repository\AuthorRepository
    xidea_book.author.loader.default.class: Xidea\Bundle\BookBundle\Doctrine\ORM\Loader\AuthorLoader
    xidea_book.author.manager.default.class: Xidea\Bundle\BookBundle\Doctrine\ORM\Manager\AuthorManager
  
services:
    xidea_book.author.repository.default:
        class: %xidea_book.author.repository.default.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %xidea_book.author.class%
    xidea_book.author.loader.default:
        class: %xidea_book.author.loader.default.class%
        arguments:
            - @xidea_book.author.repository.default
    xidea_book.author.manager.default:
        class: %xidea_book.author.manager.default.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @event_dispatcher
