parameters:
    xidea_book.author.configuration.default.class: Xidea\Bundle\BaseBundle\Configuration
    xidea_book.author.factory.default.class: Xidea\Component\Book\Factory\AuthorFactory
  
services:
    xidea_book.author.configuration.default:
        class: %xidea_book.author.configuration.default.class%
        arguments:
            - %xidea_book.author.code%
        tags:
            - { name: xidea_base.configuration }
    xidea_book.author.factory.default:
        class: %xidea_book.author.factory.default.class%
        arguments:
            - %xidea_book.author.class%