services:
    xidea_book.author.form.type:
        class: Xidea\Bundle\BookBundle\Form\Type\AuthorType
        arguments:
            - %xidea_book.author.class%
        tags:
            - { name: form.type, alias: "xidea_author" }
    xidea_book.author_create.form.factory:
        class: Xidea\Bundle\BookBundle\Form\Factory\FormFactory
        arguments:
            - @form.factory
            - %xidea_book.author_create.form.name%
            - %xidea_book.author_create.form.type%
            - %xidea_book.author_create.form.validation_groups%
    xidea_book.author_create.form.handler:
        class: Xidea\Bundle\BookBundle\Form\Handler\AuthorFormHandler
        arguments:
            - @xidea_book.author_create.form.factory
            - @event_dispatcher