parameters:
    xidea_book.controller.list.class: Xidea\Bundle\BookBundle\Controller\Book\ListController
    xidea_book.controller.show.class: Xidea\Bundle\BookBundle\Controller\Book\ShowController
    xidea_book.controller.create.class: Xidea\Bundle\BookBundle\Controller\Book\CreateController
  
services:
    xidea_book.controller.list:
        class: %xidea_book.controller.list.class%
        arguments:
            - @xidea_book.book.configuration
            - @xidea_book.book.loader
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setTemplating, [@templating]]
    xidea_book.controller.show:
        class: %xidea_book.controller.show.class%
        arguments:
            - @xidea_book.book.configuration
            - @xidea_book.book.loader
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setTemplating, [@templating]]
    xidea_book.controller.create:
        class: %xidea_book.controller.create.class%
        arguments:
            - @xidea_book.book.configuration
            - @xidea_book.book.director
            - @xidea_book.book.manager
            - @xidea_book.book.form.create.handler
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setRouter, [@router]]
            - [setTemplating, [@templating]]