parameters:
    xidea_book.book.configuration.default.class: Xidea\Bundle\BaseBundle\Configuration
    xidea_book.book.factory.default.class: Xidea\Component\Book\Factory\BookFactory
    xidea_book.book.builder.default.class: Xidea\Component\Book\Builder\BookBuilder
    xidea_book.book.director.default.class: Xidea\Component\Book\Builder\BookDirector
  
services:
    xidea_book.book.configuration.default:
        class: %xidea_book.book.configuration.default.class%
        arguments:
            - %xidea_book.book.code%
        tags:
            - { name: xidea_base.configuration }
    xidea_book.book.factory.default:
        class: %xidea_book.book.factory.default.class%
        arguments:
            - %xidea_book.book.class%
    xidea_book.book.builder.default:
        class: %xidea_book.book.builder.default.class%
        arguments:
            - @xidea_book.book.factory
    xidea_book.book.director.default:
        class: %xidea_book.book.director.default.class%
        arguments:
            - @xidea_book.book.builder