parameters:
    xidea_book.book_factory.class: Xidea\Component\Book\Factory\BookFactory
    xidea_book.book_builder.class: Xidea\Component\Book\Builder\BookBuilder
    xidea_book.book_director.class: Xidea\Component\Book\Builder\BookDirector
  
services:
    xidea_book.book_factory.default:
        class: %xidea_book.book_factory.class%
        arguments:
            - %xidea_book.book.class%
    xidea_book.book_builder.default:
        class: %xidea_book.book_builder.class%
        arguments:
            - @xidea_book.book_factory
    xidea_book.book_director.default:
        class: %xidea_book.book_director.class%
        arguments:
            - @xidea_book.book_builder
            - @xidea_book.user_provider