parameters:
    #services
    xidea_book.publisher.configuration.default.class: Xidea\Base\Configuration\DefaultConfiguration
    xidea_book.publisher.factory.default.class: Xidea\Base\Model\Factory\DefaultFactory
    #forms
    xidea_book.publisher.form.type.class: Xidea\Bundle\BookBundle\Form\Type\PublisherType
    xidea_book.publisher.form.factory.default.class: Xidea\Bundle\BaseBundle\Form\Factory\FormFactory
    xidea_book.publisher.form.handler.default.class: Xidea\Bundle\BookBundle\Form\Handler\PublisherFormHandler
  
services:
    #services
    xidea_book.publisher.configuration.default:
        class: %xidea_book.publisher.configuration.default.class%
        arguments:
            - %xidea_book.publisher.code%
        tags:
            - { name: xidea_base.configuration }
    xidea_book.publisher.factory.default:
        class: %xidea_book.publisher.factory.default.class%
        arguments:
            - %xidea_book.publisher.class%
    #forms
    xidea_book.publisher.form.type:
        class: %xidea_book.publisher.form.type.class%
        arguments:
            - %xidea_book.publisher.class%
        tags:
            - { name: form.type, alias: "xidea_publisher" }
    xidea_book.publisher.form.factory.default:
        class: %xidea_book.publisher.form.factory.default.class%
        arguments:
            - @form.factory
            - %xidea_book.publisher.form.name%
            - %xidea_book.publisher.form.type%
            - %xidea_book.publisher.form.validation_groups%
    xidea_book.publisher.form.handler.default:
        class: %xidea_book.publisher.form.handler.default.class%
        arguments:
            - @xidea_book.publisher.form.factory
            - @event_dispatcher