parameters:
    xidea_book.publisher.configuration.default.class: Xidea\Bundle\BaseBundle\Configuration
    xidea_book.publisher.factory.default.class: Xidea\Component\Book\Factory\PublisherFactory
  
services:
    xidea_book.publisher.configuration.default:
        class: %xidea_book.publisher.configuration.default.class%
        arguments:
            - %xidea_book.publisher.code%
        tags:
            - { name: xidea_base.configuration }
    xidea_book.publisher.factory.default:
        class: %xidea_book.publisher.factory.default.class%
        arguments:
            - %xidea_book.publisher.class%