parameters:
    xidea_book.publisher.repository.default.class: Xidea\Bundle\BookBundle\Doctrine\ORM\Repository\PublisherRepository
    xidea_book.publisher.loader.default.class: Xidea\Bundle\BookBundle\Doctrine\ORM\Loader\PublisherLoader
    xidea_book.publisher.manager.default.class: Xidea\Bundle\BookBundle\Doctrine\ORM\Manager\PublisherManager
  
services:
    xidea_book.publisher.repository.default:
        class: %xidea_book.publisher.repository.default.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - %xidea_book.publisher.class%
    xidea_book.publisher.loader.default:
        class: %xidea_book.publisher.loader.default.class%
        arguments:
            - @xidea_book.publisher.repository.default
    xidea_book.publisher.manager.default:
        class: %xidea_book.publisher.manager.default.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @event_dispatcher
