Xidea\Bundle\BookBundle\Model\AbstractAuthor:
    type: mappedSuperclass
    repositoryClass: Xidea\Bundle\BookBundle\Doctrine\ORM\Repository\AuthorRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
#    lifecycleCallbacks:
#        prePersist: [ prePersist ]
#        preUpdate: [ preUpdate ]