Xidea\Component\Book\Model\AbstractPublisher:
    type: mappedSuperclass
    repositoryClass: Xidea\Bundle\BookBundle\Doctrine\ORM\Repository\PublisherRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
#    lifecycleCallbacks:
#        prePersist: [ prePersist ]
#        preUpdate: [ preUpdate ]