Xidea\Component\Book\Model\AbstractBook:
    type: mappedSuperclass
    repositoryClass: Xidea\Bundle\BookBundle\Doctrine\ORM\Repository\BookRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        slug:
            type: string
            length: 255
            nullable: true
        isbn:
            type: string
            length: 64
        ean:
            type: string
            length: 64
        category:
            type: string
            length: 255
            nullable: true
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        shortDescription:
            type: string
            length: 512
            nullable: true
        series:
            type: string
            length: 255
            nullable: true
        cover:
            type: integer
            nullable: true
        premiere:
            column: premiere
            type: date
            nullable: true
        releaseYear:
            type: integer
            nullable: true
        releaseNumber:
            type: integer
            nullable: true
        pages:
            type: integer
            nullable: true
        dimensions:
            type: string
            length: 64
            nullable: true
        price:
            type: decimal
            nullable: true
        imagePath:
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            nullable: true
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
    manyToMany:
        bookAuthors:
            targetEntity: Xidea\Component\Book\Model\BookAuthorInterface
            joinTable:
                name: book_book_author
                joinColumns:
                    book_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    author_id:
                        referencedColumnName: id
                        unique: true
    manyToOne:
        publisher:
            targetEntity: Xidea\Component\Book\Model\PublisherInterface
            joinColumn:
                name: publisher_id
                referencedColumnName: id
                nullable: true
#    lifecycleCallbacks:
#        prePersist: [ prePersist ]
#        preUpdate: [ preUpdate ]